### ISSUE TITLE
Возможно ди добавить настройки конфигурации с Tapswap?

### ISSUE THREAD

**Issue by bd100b** [vherasymenk0/pocket-rocket-bot#2]
Возможно ди добавить настройки конфигурации с Tapswap?

MIN_AVAILABLE_ENERGY=
SLEEP_BY_MIN_ENERGY=

ADD_TAPS_ON_TURBO=

AUTO_UPGRADE_TAP=
MAX_TAP_LEVEL=
AUTO_UPGRADE_ENERGY=
MAX_ENERGY_LEVEL=
AUTO_UPGRADE_CHARGE=
MAX_CHARGE_LEVEL=

APPLY_DAILY_ENERGY=
APPLY_DAILY_TURBO=

RANDOM_TAPS_COUNT=
SLEEP_BETWEEN_TAP=

**Comment by vherasymenk0** [comment]
ты можешь менять значения прямо в конфиге

**Comment by bd100b** [comment]
Это все что есть значения?

    API_ID: int
    API_HASH: str

    MIN_AVAILABLE_ENERGY: int = 200
    SLEEP_BY_MIN_ENERGY: int = 200

    # max value must be less than MIN_AVAILABLE_ENERGY
    RANDOM_TAPS_COUNT: list[int] = [100, 190]
    SLEEP_BETWEEN_TAP: list[int] = [5, 10]

    USE_PROXY_FROM_FILE: bool = False
